# Generated by Django 3.1.7 on 2021-03-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210308_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='userProfile',
            new_name='organisation',
        ),
    ]
