# Generated by Django 3.1.7 on 2021-03-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisation',
            new_name='oragnization',
        ),
    ]
