# Generated by Django 3.1.7 on 2021-03-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20210320_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
