# Generated by Django 3.1.7 on 2021-03-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_category_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='categoory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category'),
        ),
    ]
