# Generated by Django 3.1.7 on 2021-03-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20210322_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='categoory',
            new_name='category',
        ),
    ]
